### ISSUE TITLE
termux

### ISSUE THREAD

**Issue by souibes** [Genplat/custoMUX#1]
After installing custoMUX, termux forces closes. A message after installation saying there was an error in line 34 if I'm not mistaken. Cant open termux all as it goes straight to a straight exit. If there is a way to fix it. I'm on redmi 9 android 14 crdroid. Thanks for any answer that could help 
![Screenshot_20240323-150905_crDroid Home](https://github.com/Genplat/custoMUX/assets/82495340/42c4f065-5275-4ce3-a3dd-e947ad5d0fc9)

**Comment by souibes** [comment]
Managed to fix it. Your mainmenu.py is missing (") on a line. To be honest, there are too many fixes to do like sound and internet to fix. The amount of 12G after install is a no for me. No root. Good luck

**Comment by Genplat** [comment]
Let me check it, i think that i didn't forgot any ("), maybe a bug of your phone or anything like it, but wait a minute, and, please, let me known the other buggy things.

Best Regards,
Genplat

**Comment by Genplat** [comment]
Done, I fixed it, please, for non-root use [this repo](https://github.com/Genplat/awesome-termux), if you found any other bug, please, create a new issue, thank you and sorry for the error, have a nice day.

Best regards,
Genplat
